Worksheet 0

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def transform_length(amount, measurement):
    """
    Convert length between meters and feet.
    :param amount: The numerical value to be transformed.
    :param measurement: The original unit ('m' for meters, 'ft' for feet).
    :return: Transformed value.
    """
    if measurement == 'm':
        return amount * 3.28084  # Convert meters to feet
    elif measurement == 'ft':
        return amount / 3.28084  # Convert feet to meters
    else:
        raise ValueError("Unsupported length measurement.")

def transform_weight(amount, measurement):
    """
    Convert weight between kilograms and pounds.
    :param amount: The numerical value to be transformed.
    :param measurement: The original unit ('kg' for kilograms, 'lbs' for pounds).
    :return: Transformed value.
    """
    if measurement == 'kg':
        return amount * 2.20462  # Convert kilograms to pounds
    elif measurement == 'lbs':
        return amount / 2.20462  # Convert pounds to kilograms
    else:
        raise ValueError("Unsupported weight measurement.")

def transform_volume(amount, measurement):
    """
    Convert volume between liters and gallons.
    :param amount: The numerical value to be transformed.
    :param measurement: The original unit ('L' for liters, 'gal' for gallons).
    :return: Transformed value.
    """
    if measurement == 'L':
        return amount * 0.264172  # Convert liters to gallons
    elif measurement == 'gal':
        return amount / 0.264172  # Convert gallons to liters
    else:
        raise ValueError("Unsupported volume measurement.")

def execute_conversion():
    """Handles user input and processes the unit transformation."""
    print("Unit Converter: Length, Weight, Volume")
    print("1. Length (meters to feet, feet to meters)")
    print("2. Weight (kilograms to pounds, pounds to kilograms)")
    print("3. Volume (liters to gallons, gallons to liters)")

    try:
        category = int(input("Select conversion type (1-3): "))
        amount = float(input("Enter value to transform: "))

        if category == 1:
            measurement = input("Enter unit ('m' for meters, 'ft' for feet): ").strip().lower()
            outcome = transform_length(amount, measurement)
            new_measurement = 'ft' if measurement == 'm' else 'm'
        elif category == 2:
            measurement = input("Enter unit ('kg' for kilograms, 'lbs' for pounds): ").strip().lower()
            outcome = transform_weight(amount, measurement)
            new_measurement = 'lbs' if measurement == 'kg' else 'kg'
        elif category == 3:
            measurement = input("Enter unit ('L' for liters, 'gal' for gallons): ").strip().lower()
            outcome = transform_volume(amount, measurement)
            new_measurement = 'gal' if measurement == 'L' else 'L'
        else:
            print("Invalid choice. Please select a valid option.")
            return

        print(f"Converted value: {outcome:.2f} {new_measurement}")

    except ValueError as err:
        print(f"Error: {err}. Please enter valid input.")

if __name__ == "__main__":
    execute_conversion()


Unit Converter: Length, Weight, Volume
1. Length (meters to feet, feet to meters)
2. Weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
Select conversion type (1-3): 2
Enter value to transform: 6
Enter unit ('kg' for kilograms, 'lbs' for pounds): kg
Converted value: 13.23 lbs


Task 2: Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def compute_total(values):
    """
    Compute the total sum of a list of values.
    :param values: List of numerical inputs.
    :return: Total sum of the values.
    """
    return sum(values)

def compute_mean(values):
    """
    Compute the average of a list of values.
    :param values: List of numerical inputs.
    :return: Mean value of the list.
    """
    return sum(values) / len(values) if values else 0  # Prevent division by zero

def get_highest_value(values):
    """
    Identify the highest number in a list.
    :param values: List of numerical inputs.
    :return: The largest number in the list.
    """
    return max(values)

def get_lowest_value(values):
    """
    Identify the lowest number in a list.
    :param values: List of numerical inputs.
    :return: The smallest number in the list.
    """
    return min(values)

def execute_math_operations():
    """Handles user input and executes the chosen mathematical operation."""
    print("Mathematical Operations on a List of Numbers")
    print("1. Total Sum")
    print("2. Average Value")
    print("3. Highest Number")
    print("4. Lowest Number")

    try:
        selection = int(input("Select an operation (1-4): "))
        values = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not values:
            raise ValueError("List is empty. At least one number is required.")

        if selection == 1:
            outcome = compute_total(values)
            operation_name = "Total Sum"
        elif selection == 2:
            outcome = compute_mean(values)
            operation_name = "Average Value"
        elif selection == 3:
            outcome = get_highest_value(values)
            operation_name = "Highest Number"
        elif selection == 4:
            outcome = get_lowest_value(values)
            operation_name = "Lowest Number"
        else:
            print("Invalid choice. Please select a valid option.")
            return

        print(f"{operation_name}: {outcome:.2f}")

    except ValueError as err:
        print(f"Error: {err}. Please enter valid numerical input.")

if __name__ == "__main__":
    execute_math_operations()

Mathematical Operations on a List of Numbers
1. Total Sum
2. Average Value
3. Highest Number
4. Lowest Number
Select an operation (1-4): 3
Enter numbers separated by spaces: 6
Highest Number: 6.00


Exercise on List Manipulation

1. Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def select_alternate_elements(sequence):
    """
    Retrieve every alternate element from the given list, beginning with the first element.
    :param sequence: List containing various elements.
    :return: A new list with every alternate element.
    """
    return sequence[::2]  # Utilize slicing to obtain every alternate element

# Example usage
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
result_list = select_alternate_elements(sample_list)
print("Output:", result_list)

Output: [1, 3, 5, 7, 9]


2. Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end]

def reverse_list(lst):
    return lst[::-1]

# Example usage
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # Example list

sublist_result = get_sublist(list, 1, 9)
print(f"Sublist from index 1 to 9: {sublist_result}")

Sublist from index 1 to 9: [2, 3, 4, 5, 6, 7, 8, 9]


Task 3: Write a Python function that reverses a list using slicing.

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end]

def reverse_list(lst):
    return lst[::-1]

# Example usage
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

reversed_list = reverse_list(list)
print(f"Reversed list: {reversed_list}")

Reversed list: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


Task 4: Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
    """
    Remove the first and last elements from the list and return the resulting sublist.
    :param lst: List of elements.
    :return: Sublist without the first and last elements.
    """
    return lst[1:-1]  # Slicing to remove the first and last elements

# Example usage
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print("Output:", output_list)  # Output: [2, 3, 4]

Output: [2, 3, 4]


5: Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst, n):
    """
    Extract the first n elements from the list using slicing.
    :param lst: List of elements.
    :param n: Number of elements to extract.
    :return: A list of the first n elements.
    """
    return lst[:n]  # Slicing to get the first n elements

# Example usage
input_list = [1, 2, 3, 4, 5]
n = 4
output_list = get_first_n(input_list, n)
print("Output:", output_list)

Output: [1, 2, 3, 4]


7. Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [ ]:
def reverse_alternate_elements(seq):
    """
    Extract every second item starting from the second-to-last and moving backward through the sequence.
    :param seq: List of items.
    :return: A list of every second item in reverse order, starting from the second-to-last.
    """
    return seq[-2::-2]  # Slice to obtain every second element starting from the second-to-last, moving backward.

# Example usage
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
result_list = reverse_alternate_elements(sample_list)
print("Result:", result_list)


Result: [8, 6, 4, 2]


Exercise on Nested Loop

Task 1: Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [ ]:
from collections.abc import Iterable

def flatten_list(nested_list):
    """Recursively flattens a nested list into a single list."""
    flat_list = []
    for item in nested_list:
        if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
            flat_list.extend(flatten_list(item))
        else:
            flat_list.append(item)
    return flat_list

# Example usage:
nested = [1, [2, [3, 4], 5], [6, 7], 8]
flattened = flatten_list(nested)
print(flattened)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


Task 2: Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def extract_element(nested_list, indices):
    """Extracts an element from a nested list using a list of indices."""
    element = nested_list
    for index in indices:
        element = element[index]
    return element

# Example usage:
nested = [1, [2, [3, 4], 5], [6, 7], 8]
indices = [1, 1, 0]  # Accessing nested[1][1][0] → 3
result = extract_element(nested, indices)
print(result)


3


Task 3: Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
from collections.abc import Iterable

def sum_nested_list(nested_list):
    """
    Recursively calculates the sum of all numbers in a nested list.

    Parameters:
    nested_list (list): A nested list containing integers or other lists.

    Returns:
    int: The sum of all numbers in the nested list.


    """
    total = 0
    for item in nested_list:
        if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
            total += sum_nested_list(item)  # Recursively sum nested lists
        elif isinstance(item, (int, float)):  # Ensure only numbers are added
            total += item
    return total

# Example usage:
nested = [1, [2, [3, 4], 5], [6, 7], 8]
result = sum_nested_list(nested)
print(result)


36


Task 4: Write a Python function that removes all occurrences of a specific element from a nested list.

In [ ]:
from collections.abc import Iterable

def remove_element(nested_list, target):
    """
    Recursively removes all occurrences of a specific element from a nested list.

    Parameters:
    nested_list (list): A nested list containing elements or other lists.
    target (any): The element to be removed from the nested list.

    Returns:
    list: A new nested list with the target element removed.


    """
    cleaned_list = []
    for item in nested_list:
        if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
            cleaned_list.append(remove_element(item, target))  # Recursively process sublists
        elif item != target:
            cleaned_list.append(item)  # Keep elements that are not the target
    return cleaned_list

# Example usage:
nested = [1, [2, [3, 4], 5], [6, 7, 3], 3]
result = remove_element(nested, 3)
print(result)


[1, [2, [4], 5], [6, 7]]


Task 5: Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
from collections.abc import Iterable

def max_in_nested_list(nested_list):
    """
    Recursively finds the maximum element in a nested list.

    Parameters:
    nested_list (list): A nested list containing integers or other lists.

    Returns:
    int/float: The maximum number found in the nested list.


    """
    max_value = float('-inf')  # Initialize with negative infinity

    for item in nested_list:
        if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
            max_value = max(max_value, max_in_nested_list(item))  # Recursively find max in sublists
        elif isinstance(item, (int, float)):  # Only compare numbers
            max_value = max(max_value, item)

    return max_value

# Example usage:
nested = [1, [2, [3, 9], 5], [6, 7], 8]
result = max_in_nested_list(nested)
print(result)


9


Task 6: Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
from collections.abc import Iterable

def count_element(nested_list, target):
    """
    Recursively counts occurrences of a specific element in a nested list.

    Parameters:
    nested_list (list): A nested list containing elements or other lists.
    target (any): The element to count occurrences of.

    Returns:
    int: The number of times the target element appears in the nested list.


    """
    count = 0
    for item in nested_list:
        if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
            count += count_element(item, target)  # Recursively count in sublists
        elif item == target:
            count += 1  # Increment count for matching elements
    return count

# Example usage:
nested = [1, [2, [3, 4, 3], 5], [6, 7, 3], 3]
result = count_element(nested, 3)
print(result)


4


Task 7: Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
from collections.abc import Iterable

def flatten_deeply_nested_list(nested_list):
    """
    Recursively flattens a deeply nested list into a single list.

    Parameters:
    nested_list (list): A nested list containing elements or other lists.

    Returns:
    list: A flattened list with all elements in a single dimension.


    """
    flat_list = []
    for item in nested_list:
        if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
            flat_list.extend(flatten_deeply_nested_list(item))  # Recursively flatten sublists
        else:
            flat_list.append(item)
    return flat_list

# Example usage:
nested = [1, [2, [3, [4, 5]], [6, 7]], 8]
flattened = flatten_deeply_nested_list(nested)
print(flattened)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


Task 8: Write a Python function that calculates the average of all elements in a nested list

In [ ]:
from collections.abc import Iterable

def average_of_nested_list(nested_list):
    """
    Recursively calculates the average of all numerical elements in a nested list.

    Parameters:
    nested_list (list): A nested list containing numbers or other lists.

    Returns:
    float: The average of all numbers in the nested list.

    """
    def helper(nested_list):
        total = 0
        count = 0
        for item in nested_list:
            if isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
                sub_total, sub_count = helper(item)  # Recursively process sublists
                total += sub_total
                count += sub_count
            elif isinstance(item, (int, float)):  # Only count numbers
                total += item
                count += 1
        return total, count

    total, count = helper(nested_list)
    return total / count if count > 0 else 0  # Avoid division by zero

# Example usage:
nested = [1, [2, [3, 4], 5], [6, 7], 8]
result = average_of_nested_list(nested)
print(result)


4.5


Numpy

Array Creation

Task 1: Initialize an empty array with size 2x2:

In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[2.16435555e-316 0.00000000e+000]
 [6.59737730e-310 4.86622250e-317]]


Task 2: Initialize an empty array with size 4x2:

In [ ]:
ones_array = np.ones((4, 2))
print("All Ones Array:\n", ones_array)

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Task 3: Return a new array of a given shape and type, filled with a fill value:

In [ ]:

value_array = np.full((3, 3), 7)
print("\nArray filled with a specific value (7):")
print(value_array)


Array filled with a specific value (7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]


Task 4: Return a new array of zeros with the same shape and type as a given array:

In [ ]:
template_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(template_array)
print("Zeros Array with Same Shape and Type:\n", zeros_array)

Zeros Array with Same Shape and Type:
 [[0 0]
 [0 0]]


Task 5: Return a new array of ones with the same shape and type as a given array:

In [ ]:
ones_like_array = np.ones_like(template_array)
print("Ones Array with Same Shape and Type:\n", ones_like_array)

Ones Array with Same Shape and Type:
 [[1 1]
 [1 1]]


Task 6: Convert an existing list new_list = [1, 2, 3, 4] to a numpy array:

In [ ]:
my_list = [1, 2, 3, 4]
numpy_array = np.array(my_list)
print("\nConverted NumPy array from list:")
print(numpy_array)


Converted NumPy array from list:
[1 2 3 4]


Problem 2: Array Manipulation

Task 1: Create an array with values ranging from 10 to 49.

In [ ]:
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 2: Create a 3x3 matrix with values ranging from 0 to 8.

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:")
print(matrix_3x3)


3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 3: Create a 3x3 identity matrix.

In [ ]:
identity_matrix = np.eye(3)
print("\n3x3 identity matrix:")
print(identity_matrix)


3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 4: Create a random array of size 30 and find the mean of the array.

In [ ]:
random_array = np.random.rand(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:")
print(random_array)
print(f"Mean of the random array: {mean_value}")
random_10x10 = np.random.rand(10, 10)


Random array of size 30:
[0.1575055  0.12165809 0.12621775 0.60913116 0.1331528  0.77214796
 0.83722178 0.19630245 0.95369098 0.06037495 0.19001552 0.87593355
 0.68179256 0.53493463 0.1189189  0.29039223 0.06761627 0.34895372
 0.92532053 0.19533815 0.55856304 0.0149676  0.89618083 0.37577589
 0.51912405 0.97058304 0.93338657 0.18382834 0.8107     0.35882603]
Mean of the random array: 0.46061849569587693


Task 5: Create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 random array:")
print(random_10x10)
print(f"Min value: {min_value}")
print(f"Max value: {max_value}")


10x10 random array:
[[8.29205051e-01 5.38225792e-01 3.42480168e-01 3.33637047e-01
  2.06180729e-01 9.64796099e-01 4.68911206e-02 6.49788725e-01
  8.18368844e-01 1.01721281e-01]
 [4.32191759e-01 4.91243026e-01 9.00623182e-01 9.00913019e-01
  4.05896881e-01 7.60760937e-01 5.80393631e-01 1.24002848e-01
  9.95877183e-02 2.55287325e-01]
 [8.59592543e-01 5.99652060e-01 2.71845610e-01 9.65396005e-01
  1.10093938e-01 7.02843275e-01 8.28613405e-01 6.03424456e-01
  2.84419868e-01 1.78260615e-01]
 [3.75880790e-01 9.29163215e-01 4.67322662e-01 7.07093745e-01
  8.73626701e-01 6.95566364e-01 7.35973150e-01 1.24696807e-01
  3.05487199e-02 6.50373012e-01]
 [9.80623107e-01 9.60819705e-01 7.30372379e-01 3.38110808e-01
  6.97687881e-01 8.83304194e-02 9.91493214e-01 2.11105313e-01
  9.01131568e-01 7.59533475e-02]
 [2.58908683e-02 9.52190824e-01 3.01936354e-01 5.39514950e-01
  3.35633247e-01 2.46793432e-01 5.84013185e-01 1.33824337e-01
  5.89633919e-01 5.28941148e-01]
 [6.36022957e-01 9.62593643e-02 2.536

Task 6: Create a zero array of size 10 and replace the 5th element with 1.

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 corresponds to the 5th element
print("Zero Array with 5th Element as 1:\n", zero_array)

Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 7: Reverse an array

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


Task 8: Create a 2D array with 1 on the border and 0 inside:

In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on Border and 0 Inside:\n", border_array)

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern:

In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem 3: Array Operations

For the following arrays:

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

Task 1: Add the two arrays x and y.

In [ ]:
sum_array = x + y
print("Sum of Arrays x and y:\n", sum_array)

Sum of Arrays x and y:
 [[ 6  8]
 [10 13]]


Task 2: Subtract the two arrays x and y.

In [ ]:
sub_array = x - y
print("Subraction of Arrays x and y:\n", sub_array)

Subraction of Arrays x and y:
 [[-4 -4]
 [-4 -3]]


Task 3: Multiply the array x with an integer of your choice.

In [ ]:
multiplied_array = x * 3  # with 3
print("Array x Multiplied by 3:\n", multiplied_array)

Array x Multiplied by 3:
 [[ 3  6]
 [ 9 15]]


Task 4: Find the square of each element of the array x.

In [ ]:
squared_array = np.square(x)
print("Square of Each Element in Array x:\n", squared_array)

Square of Each Element in Array x:
 [[ 1  4]
 [ 9 25]]


Task 5: Find the dot product.

In [ ]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


Task 6 : Concatenate x and y along rows and concatenate v and w along columns:

In [ ]:
concatenated_xy_row = np.concatenate((x, y), axis=0)
concatenated_vw_col = np.concatenate((v[:, None], w[:, None]), axis=1)
print("Concatenated x and y along rows:\n", concatenated_xy_row)
print("Concatenated v and w along columns:\n", concatenated_vw_col)

Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]


Problem 4: Matrix Operations

For the following matrices:

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

Task 1: Prove that A * A^(-1) = I.

In [ ]:
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1) = I:\n", identity_matrix)

A * A^(-1) = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


Task 2: Prove that AB ≠ BA.

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


Task 3: Prove that (AB)^T = B^T * A^T.

In [ ]:
transpose_AB = np.transpose(np.dot(A, B))
transpose_BA = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", transpose_AB)
print("B^T * A^T:\n", transpose_BA)

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]


Task 4: Solve the system of linear equations using inverse methods

In [ ]:
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

X = np.linalg.inv(A_eq).dot(B_eq)
print("Solution using Inverse Method:", X)

Solution using Inverse Method: [ 2.  1. -2.]


Problem 5: How Fast is Numpy?

Task 1: Element-wise Addition:

In [ ]:
import time

# Using Python Lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(1000000)]
print("Python List Addition Time:", time.time() - start_time)

# Using NumPy Arrays
array1 = np.array(list1)
array2 = np.array(list2)
start_time = time.time()
numpy_addition = array1 + array2
print("NumPy Array Addition Time:", time.time() - start_time)


Python List Addition Time: 0.050364017486572266
NumPy Array Addition Time: 0.003036022186279297


Task 2: Element-wise Multiplication:

In [ ]:
# Using Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(1000000)]
print("Python List Multiplication Time:", time.time() - start_time)

# Using NumPy Arrays
start_time = time.time()
numpy_multiplication = array1 * array2
print("NumPy Array Multiplication Time:", time.time() - start_time)

Python List Multiplication Time: 0.057309865951538086
NumPy Array Multiplication Time: 0.0027158260345458984


Task 3: Dot Product:

In [ ]:
# Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
print("Python List Dot Product Time:", time.time() - start_time)

# Using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
print("NumPy Array Dot Product Time:", time.time() - start_time)

Python List Dot Product Time: 0.07437896728515625
NumPy Array Dot Product Time: 0.0010187625885009766


Task 4: Matrix Multiplication

4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [50]:
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i + j for j in range(1000)] for i in range(1000)]

start = time.time()
mul_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)]
              for row in matrix1]

print("Python list matrix multiplication:", time.time() - start)

Python list matrix multiplication: 78.67297744750977
Python list matrix multiplication: 86.34152150154114


In [51]:
np_matrix1 = np.random.random((1000, 1000))
np_matrix2 = np.random.random((1000,1000))

start = time.time()
mul_matrix = np.dot(matrix1, matrix2)

print("Numpy array matrix multiplication:", time.time() - start)

Numpy array matrix multiplication: 1.0945000648498535
